/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.MiddleWare;
import java.awt.GridLayout;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JEditorPane;
import javax.swing.JOptionPane;
import wiki.DataModel.StoreData.CreateUserInformation;
import wiki.DataModel.StoreData.ReadUserInformation;

/**
 *
 * @author Mainul35
 */
public class TutorPanel extends javax.swing.JFrame {

    /**
     * Creates new form UserPanel
     */
    private String pageTitle = null;
    
    private StringBuilder pageContent = null;

    public TutorPanel() {
        editorPane = new JEditorPane();
        try {
            initComponents();
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
//            try {
                lblUserName.setText(TutorLoginWindow.txtUserName.getText());
                editorPane.setEditable(false);
//                editorPane.setPage("http://www.yoursite.com");
//            }catch (IOException e) {
//                e.printStackTrace();
                editorPane.setContentType("text/html");
//          editorPane.setText(parseHyperText);
//            }
            if(ReadUserInformation.hasWritePermission(TutorLoginWindow.getTxtUserName().getText()).equalsIgnoreCase("True")){
                tAreaPageContent.setEditable(true);
                btnPreview.setEnabled(true);
                btnSavePageContent.setEnabled(true);
            }else if(ReadUserInformation.hasWritePermission(TutorLoginWindow.getTxtUserName().getText()).equalsIgnoreCase("False")){
                tAreaPageContent.setEditable(false);
                btnPreview.setEnabled(false);
                btnSavePageContent.setEnabled(false);
        }
        }catch (SQLException ex) {
            ex.printStackTrace();
            Logger.getLogger(TutorPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        pnlBlogsOfAdmins.setLayout(new GridLayout());
        pnlBlogsOfAdmins.add(new AdminWikiPanel("Tutor", MiddleWare.uname));
        pnlBlogsOfAdmins.repaint();
        pnlBlogOfTutors.setLayout(new GridLayout());
        pnlBlogOfTutors.add(new TutorWikiPanel("Tutor", MiddleWare.uname));
        pnlBlogOfTutors.repaint();
        pnlBlogOfStudents.setLayout(new GridLayout());
        pnlBlogOfStudents.add(new StudentWikiPanel("Tutor", MiddleWare.uname));
        pnlBlogOfStudents.repaint();
        this.setTitle("Tutor panel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblUserName = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pnlBlogsOfAdmins = new javax.swing.JPanel();
        pnlBlogOfTutors = new javax.swing.JPanel();
        pnlBlogOfStudents = new javax.swing.JPanel();
        pnlEditPage = new javax.swing.JPanel();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane2 = new javax.swing.JScrollPane();
        tAreaPageContent = new javax.swing.JTextArea();
        txtTitleBar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel72 = new javax.swing.JLabel();
        jLabel73 = new javax.swing.JLabel();
        jLabel74 = new javax.swing.JLabel();
        jLabel75 = new javax.swing.JLabel();
        jLabel76 = new javax.swing.JLabel();
        jLabel77 = new javax.swing.JLabel();
        jLabel78 = new javax.swing.JLabel();
        jLabel79 = new javax.swing.JLabel();
        jLabel80 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        jLabel82 = new javax.swing.JLabel();
        jLabel83 = new javax.swing.JLabel();
        btnPreview = new javax.swing.JButton();
        btnSavePageContent = new javax.swing.JButton();
        pnlWritePage = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        editorPane = new javax.swing.JEditorPane();
        btnLogOut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblUserRole = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Logged in as :");

        javax.swing.GroupLayout pnlBlogsOfAdminsLayout = new javax.swing.GroupLayout(pnlBlogsOfAdmins);
        pnlBlogsOfAdmins.setLayout(pnlBlogsOfAdminsLayout);
        pnlBlogsOfAdminsLayout.setHorizontalGroup(
            pnlBlogsOfAdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        pnlBlogsOfAdminsLayout.setVerticalGroup(
            pnlBlogsOfAdminsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Admin Blog", pnlBlogsOfAdmins);

        javax.swing.GroupLayout pnlBlogOfTutorsLayout = new javax.swing.GroupLayout(pnlBlogOfTutors);
        pnlBlogOfTutors.setLayout(pnlBlogOfTutorsLayout);
        pnlBlogOfTutorsLayout.setHorizontalGroup(
            pnlBlogOfTutorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        pnlBlogOfTutorsLayout.setVerticalGroup(
            pnlBlogOfTutorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Tutor Blog", pnlBlogOfTutors);

        javax.swing.GroupLayout pnlBlogOfStudentsLayout = new javax.swing.GroupLayout(pnlBlogOfStudents);
        pnlBlogOfStudents.setLayout(pnlBlogOfStudentsLayout);
        pnlBlogOfStudentsLayout.setHorizontalGroup(
            pnlBlogOfStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 741, Short.MAX_VALUE)
        );
        pnlBlogOfStudentsLayout.setVerticalGroup(
            pnlBlogOfStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Student Blog", pnlBlogOfStudents);

        jInternalFrame1.setVisible(true);

        tAreaPageContent.setColumns(20);
        tAreaPageContent.setRows(5);
        jScrollPane2.setViewportView(tAreaPageContent);

        jLabel3.setText("Page Title :");

        jPanel8.setBackground(new java.awt.Color(204, 204, 255));

        jLabel72.setText("^^....^^ ");

        jLabel73.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel73.setText("Bold");

        jLabel74.setText("//......// ");

        jLabel75.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel75.setText("Italic");

        jLabel76.setText("__.....__ ");

        jLabel77.setText("<html><u>Underlined</u></html>");

        jLabel78.setText("##.....## ");

        jLabel79.setText("<html><blockquote>Blockquotted</blockquote><html>");

        jLabel80.setText("~~");

        jLabel81.setText("Jump to next line");

        jLabel82.setText("--......--");

        jLabel83.setText("Center");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel78)
                                    .addComponent(jLabel80, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel81)
                                        .addGap(22, 22, 22))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel83)
                                        .addGap(47, 47, 47))))
                            .addComponent(jLabel82)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel74)
                                    .addComponent(jLabel72))
                                .addGap(63, 63, 63)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel75)
                                    .addComponent(jLabel73))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel76)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel72)
                    .addComponent(jLabel73))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel74)
                    .addComponent(jLabel75))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel76)
                    .addComponent(jLabel77, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel78)
                    .addComponent(jLabel79, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel80)
                    .addComponent(jLabel81))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel82)
                    .addComponent(jLabel83))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitleBar))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTitleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnPreview.setText("Preview");
        btnPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviewActionPerformed(evt);
            }
        });

        btnSavePageContent.setText("Save");
        btnSavePageContent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSavePageContentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditPageLayout = new javax.swing.GroupLayout(pnlEditPage);
        pnlEditPage.setLayout(pnlEditPageLayout);
        pnlEditPageLayout.setHorizontalGroup(
            pnlEditPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEditPageLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPreview)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSavePageContent)
                .addContainerGap())
        );
        pnlEditPageLayout.setVerticalGroup(
            pnlEditPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditPageLayout.createSequentialGroup()
                .addComponent(jInternalFrame1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPreview)
                    .addComponent(btnSavePageContent))
                .addContainerGap())
        );

        tabbedPane.addTab("Page", pnlEditPage);

        jScrollPane1.setViewportView(editorPane);

        javax.swing.GroupLayout pnlWritePageLayout = new javax.swing.GroupLayout(pnlWritePage);
        pnlWritePage.setLayout(pnlWritePageLayout);
        pnlWritePageLayout.setHorizontalGroup(
            pnlWritePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 741, Short.MAX_VALUE)
        );
        pnlWritePageLayout.setVerticalGroup(
            pnlWritePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
        );

        tabbedPane.addTab("Preview page", pnlWritePage);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 396, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnLogOut.setText("Log Out");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        jLabel2.setText("Username :");

        lblUserRole.setText("Tutor");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(lblUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLogOut)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnLogOut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUserRole, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblUserName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviewActionPerformed
        // TODO add your handling code here:
        pageTitle = txtTitleBar.getText();
        pageContent = new StringBuilder(MarkdownProcessor.MarkdownProcessor.getMarkupText(tAreaPageContent.getText()));
        
        String parseHyperText = "<html>"
                + "<head>"
                + "<title>"
                + pageTitle
                + "</title>"
                + "<head>"
                + "<body>"
                + pageContent
                + "</body>"
                + "</html>";

        tabbedPane.setSelectedIndex(4);
        editorPane.setEditable(false);
        editorPane.setText(parseHyperText);
//        JOptionPane.showMessageDialog(null, parseHyperText);
    }//GEN-LAST:event_btnPreviewActionPerformed

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        MiddleWare.getMainWindowInstance().setVisible(true);
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnSavePageContentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSavePageContentActionPerformed
        // TODO add your handling code here:
        pageTitle = txtTitleBar.getText();
        pageContent = new StringBuilder(MarkdownProcessor.MarkdownProcessor.getMarkupText(tAreaPageContent.getText()));
        String parseHyperText = "<html>"
                + "<head>"
                + "<title>"
                + pageTitle
                + "</title>"
                + "</head>"
                + "<body>"
                + pageContent
                + "</body>"
                + "</html>";

        String dir = lblUserRole.getText() + "\\" + lblUserName.getText();
        CreateUserInformation.createDirectory(dir);
        StringBuilder title = new StringBuilder(txtTitleBar.getText());
        for (int p = 0; p < title.length(); p++) {
            if (title.charAt(p) == ' ') {
                title.replace(p, p + 1, "");
            }
        }
        String URI = "Wiki\\" + dir + "\\" + title.toString() + "_0_.html";
        String tempUri = "Wiki\\" + dir + "\\" + title.toString() + "_0_.txt";
//        FileWriter writer = null;
        try {
            File f = new File(URI);

            boolean isFileAvailable = f.exists();
            if (!isFileAvailable) {
                FileOutputStream fos = new FileOutputStream(URI);
                MiddleWare.createNewPage(lblUserRole.getText(), lblUserName.getText(), txtTitleBar.getText(), URI, 0);
                
                byte[] b = parseHyperText.getBytes();
                fos.write(b);
                
                fos = new FileOutputStream(tempUri);
                b = pageContent.toString().getBytes();
                fos.write(b);
                
                fos.close();
            } else if (isFileAvailable) {
                String pageTitle = MiddleWare.readVersionData.getPageTitleByURI(URI);
                int latestVersion = MiddleWare.readVersionData.getLatestVersion(lblUserName.getText(), pageTitle);
                latestVersion += 1;
                URI = "Wiki\\" + dir + "\\" + title.toString() + "_" + latestVersion + "_.html";
                tempUri = "Wiki\\" + dir + "\\" + title.toString() + "_" + latestVersion + "_.txt";
                MiddleWare.createVersionData.addPageVersion(lblUserRole.getText(), lblUserName.getText(), txtTitleBar.getText(), URI, latestVersion);
                FileOutputStream fos = new FileOutputStream(URI);
                byte[] b = parseHyperText.getBytes();
                fos.write(b);
                
                fos = new FileOutputStream(tempUri);
                b = parseHyperText.getBytes();
                fos.write(b);
                
                fos.close();
            }
            JOptionPane.showMessageDialog(null, "The page has been saved successfully!");
//            }
        } catch (IOException ex) {
            ex.printStackTrace();
            Logger.getLogger(CreateUserInformation.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSavePageContentActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnPreview;
    private javax.swing.JButton btnSavePageContent;
    public static javax.swing.JEditorPane editorPane;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel72;
    private javax.swing.JLabel jLabel73;
    private javax.swing.JLabel jLabel74;
    private javax.swing.JLabel jLabel75;
    private javax.swing.JLabel jLabel76;
    private javax.swing.JLabel jLabel77;
    private javax.swing.JLabel jLabel78;
    private javax.swing.JLabel jLabel79;
    private javax.swing.JLabel jLabel80;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel82;
    private javax.swing.JLabel jLabel83;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JLabel lblUserRole;
    private javax.swing.JPanel pnlBlogOfStudents;
    private javax.swing.JPanel pnlBlogOfTutors;
    private javax.swing.JPanel pnlBlogsOfAdmins;
    private javax.swing.JPanel pnlEditPage;
    private javax.swing.JPanel pnlWritePage;
    private javax.swing.JTextArea tAreaPageContent;
    public static javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtTitleBar;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the lblUserName
     */
    public javax.swing.JLabel getLblUserName() {
        return lblUserName;
    }
}
